[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.5.0"
proc-macro2 = "1.0.40"
quote = "1"
syn = { version = "1", features = ["full"] }

[lib]
proc-macro = true
